version: '3'
services:
  dockermariadb:
    container_name: dockermariadb
    build:
      context: ./
      dockerfile: MariaDb.dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_NAME}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_NAME}
      MYSQL_TCP_PORT: 3306
    restart: always
    volumes: 
      - "${MYSQL_DATA_DIR}:/var/lib/mysql:rw"
      - "${MYSQL_LOGS_DIR}:/var/log/mysql:rw"
  dockerphpmyadmin:
    container_name: dockerphpmyadmin
    build:
      context: ./
      dockerfile: PhpMyAdmin.dockerfile
    restart: always
    ports:
      - 8080:80
    links:
      - dockermariadb
    environment:
      PMA_HOST: dockermariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 3000M